/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OrgIdRouteImport } from './routes/$orgId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConstructionOrgIdTeamsRouteImport } from './routes/construction.$orgId/teams'
import { Route as ConstructionOrgIdSettingsRouteImport } from './routes/construction.$orgId/settings'
import { Route as ConstructionOrgIdProjectsRouteImport } from './routes/construction.$orgId/projects'
import { Route as ConstructionOrgIdMembersRouteImport } from './routes/construction.$orgId/members'
import { Route as ConstructionOrgIdConstructionTeamsRouteImport } from './routes/construction.$orgId/construction-teams'
import { Route as ConstructionOrgIdConstructionTasksRouteImport } from './routes/construction.$orgId/construction-tasks'
import { Route as ConstructionOrgIdConstructionProjectsRouteImport } from './routes/construction.$orgId/construction-projects'
import { Route as ConstructionOrgIdConstructionDocumentsRouteImport } from './routes/construction.$orgId/construction-documents'
import { Route as ConstructionOrgIdConstructionDashboardRouteImport } from './routes/construction.$orgId/construction-dashboard'
import { Route as ConstructionOrgIdAttachmentsRouteImport } from './routes/construction.$orgId/attachments'
import { Route as ConstructionOrgIdAdminRouteImport } from './routes/construction.$orgId/admin'
import { Route as ConstructionOrgIdTeamTeamIdRouteImport } from './routes/construction.$orgId/team.$teamId'
import { Route as ConstructionOrgIdTeamTeamIdAllRouteImport } from './routes/construction.$orgId/team.$teamId.all'
import { Route as ConstructionOrgIdProjectsProjectIdTeamRouteImport } from './routes/construction.$orgId/projects.$projectId.team'
import { Route as ConstructionOrgIdProjectsProjectIdTasksRouteImport } from './routes/construction.$orgId/projects.$projectId.tasks'
import { Route as ConstructionOrgIdProjectsProjectIdSettingsRouteImport } from './routes/construction.$orgId/projects.$projectId.settings'
import { Route as ConstructionOrgIdProjectsProjectIdOverviewRouteImport } from './routes/construction.$orgId/projects.$projectId.overview'
import { Route as ConstructionOrgIdProjectsProjectIdAnalyticsRouteImport } from './routes/construction.$orgId/projects.$projectId.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdRoute = OrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionOrgIdTeamsRoute = ConstructionOrgIdTeamsRouteImport.update({
  id: '/construction/$orgId/teams',
  path: '/construction/$orgId/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionOrgIdSettingsRoute =
  ConstructionOrgIdSettingsRouteImport.update({
    id: '/construction/$orgId/settings',
    path: '/construction/$orgId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdProjectsRoute =
  ConstructionOrgIdProjectsRouteImport.update({
    id: '/construction/$orgId/projects',
    path: '/construction/$orgId/projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdMembersRoute =
  ConstructionOrgIdMembersRouteImport.update({
    id: '/construction/$orgId/members',
    path: '/construction/$orgId/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdConstructionTeamsRoute =
  ConstructionOrgIdConstructionTeamsRouteImport.update({
    id: '/construction/$orgId/construction-teams',
    path: '/construction/$orgId/construction-teams',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdConstructionTasksRoute =
  ConstructionOrgIdConstructionTasksRouteImport.update({
    id: '/construction/$orgId/construction-tasks',
    path: '/construction/$orgId/construction-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdConstructionProjectsRoute =
  ConstructionOrgIdConstructionProjectsRouteImport.update({
    id: '/construction/$orgId/construction-projects',
    path: '/construction/$orgId/construction-projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdConstructionDocumentsRoute =
  ConstructionOrgIdConstructionDocumentsRouteImport.update({
    id: '/construction/$orgId/construction-documents',
    path: '/construction/$orgId/construction-documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdConstructionDashboardRoute =
  ConstructionOrgIdConstructionDashboardRouteImport.update({
    id: '/construction/$orgId/construction-dashboard',
    path: '/construction/$orgId/construction-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdAttachmentsRoute =
  ConstructionOrgIdAttachmentsRouteImport.update({
    id: '/construction/$orgId/attachments',
    path: '/construction/$orgId/attachments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdAdminRoute = ConstructionOrgIdAdminRouteImport.update({
  id: '/construction/$orgId/admin',
  path: '/construction/$orgId/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionOrgIdTeamTeamIdRoute =
  ConstructionOrgIdTeamTeamIdRouteImport.update({
    id: '/construction/$orgId/team/$teamId',
    path: '/construction/$orgId/team/$teamId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConstructionOrgIdTeamTeamIdAllRoute =
  ConstructionOrgIdTeamTeamIdAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => ConstructionOrgIdTeamTeamIdRoute,
  } as any)
const ConstructionOrgIdProjectsProjectIdTeamRoute =
  ConstructionOrgIdProjectsProjectIdTeamRouteImport.update({
    id: '/$projectId/team',
    path: '/$projectId/team',
    getParentRoute: () => ConstructionOrgIdProjectsRoute,
  } as any)
const ConstructionOrgIdProjectsProjectIdTasksRoute =
  ConstructionOrgIdProjectsProjectIdTasksRouteImport.update({
    id: '/$projectId/tasks',
    path: '/$projectId/tasks',
    getParentRoute: () => ConstructionOrgIdProjectsRoute,
  } as any)
const ConstructionOrgIdProjectsProjectIdSettingsRoute =
  ConstructionOrgIdProjectsProjectIdSettingsRouteImport.update({
    id: '/$projectId/settings',
    path: '/$projectId/settings',
    getParentRoute: () => ConstructionOrgIdProjectsRoute,
  } as any)
const ConstructionOrgIdProjectsProjectIdOverviewRoute =
  ConstructionOrgIdProjectsProjectIdOverviewRouteImport.update({
    id: '/$projectId/overview',
    path: '/$projectId/overview',
    getParentRoute: () => ConstructionOrgIdProjectsRoute,
  } as any)
const ConstructionOrgIdProjectsProjectIdAnalyticsRoute =
  ConstructionOrgIdProjectsProjectIdAnalyticsRouteImport.update({
    id: '/$projectId/analytics',
    path: '/$projectId/analytics',
    getParentRoute: () => ConstructionOrgIdProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdRoute
  '/auth': typeof AuthRoute
  '/construction/$orgId/admin': typeof ConstructionOrgIdAdminRoute
  '/construction/$orgId/attachments': typeof ConstructionOrgIdAttachmentsRoute
  '/construction/$orgId/construction-dashboard': typeof ConstructionOrgIdConstructionDashboardRoute
  '/construction/$orgId/construction-documents': typeof ConstructionOrgIdConstructionDocumentsRoute
  '/construction/$orgId/construction-projects': typeof ConstructionOrgIdConstructionProjectsRoute
  '/construction/$orgId/construction-tasks': typeof ConstructionOrgIdConstructionTasksRoute
  '/construction/$orgId/construction-teams': typeof ConstructionOrgIdConstructionTeamsRoute
  '/construction/$orgId/members': typeof ConstructionOrgIdMembersRoute
  '/construction/$orgId/projects': typeof ConstructionOrgIdProjectsRouteWithChildren
  '/construction/$orgId/settings': typeof ConstructionOrgIdSettingsRoute
  '/construction/$orgId/teams': typeof ConstructionOrgIdTeamsRoute
  '/construction/$orgId/team/$teamId': typeof ConstructionOrgIdTeamTeamIdRouteWithChildren
  '/construction/$orgId/projects/$projectId/analytics': typeof ConstructionOrgIdProjectsProjectIdAnalyticsRoute
  '/construction/$orgId/projects/$projectId/overview': typeof ConstructionOrgIdProjectsProjectIdOverviewRoute
  '/construction/$orgId/projects/$projectId/settings': typeof ConstructionOrgIdProjectsProjectIdSettingsRoute
  '/construction/$orgId/projects/$projectId/tasks': typeof ConstructionOrgIdProjectsProjectIdTasksRoute
  '/construction/$orgId/projects/$projectId/team': typeof ConstructionOrgIdProjectsProjectIdTeamRoute
  '/construction/$orgId/team/$teamId/all': typeof ConstructionOrgIdTeamTeamIdAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdRoute
  '/auth': typeof AuthRoute
  '/construction/$orgId/admin': typeof ConstructionOrgIdAdminRoute
  '/construction/$orgId/attachments': typeof ConstructionOrgIdAttachmentsRoute
  '/construction/$orgId/construction-dashboard': typeof ConstructionOrgIdConstructionDashboardRoute
  '/construction/$orgId/construction-documents': typeof ConstructionOrgIdConstructionDocumentsRoute
  '/construction/$orgId/construction-projects': typeof ConstructionOrgIdConstructionProjectsRoute
  '/construction/$orgId/construction-tasks': typeof ConstructionOrgIdConstructionTasksRoute
  '/construction/$orgId/construction-teams': typeof ConstructionOrgIdConstructionTeamsRoute
  '/construction/$orgId/members': typeof ConstructionOrgIdMembersRoute
  '/construction/$orgId/projects': typeof ConstructionOrgIdProjectsRouteWithChildren
  '/construction/$orgId/settings': typeof ConstructionOrgIdSettingsRoute
  '/construction/$orgId/teams': typeof ConstructionOrgIdTeamsRoute
  '/construction/$orgId/team/$teamId': typeof ConstructionOrgIdTeamTeamIdRouteWithChildren
  '/construction/$orgId/projects/$projectId/analytics': typeof ConstructionOrgIdProjectsProjectIdAnalyticsRoute
  '/construction/$orgId/projects/$projectId/overview': typeof ConstructionOrgIdProjectsProjectIdOverviewRoute
  '/construction/$orgId/projects/$projectId/settings': typeof ConstructionOrgIdProjectsProjectIdSettingsRoute
  '/construction/$orgId/projects/$projectId/tasks': typeof ConstructionOrgIdProjectsProjectIdTasksRoute
  '/construction/$orgId/projects/$projectId/team': typeof ConstructionOrgIdProjectsProjectIdTeamRoute
  '/construction/$orgId/team/$teamId/all': typeof ConstructionOrgIdTeamTeamIdAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgId': typeof OrgIdRoute
  '/auth': typeof AuthRoute
  '/construction/$orgId/admin': typeof ConstructionOrgIdAdminRoute
  '/construction/$orgId/attachments': typeof ConstructionOrgIdAttachmentsRoute
  '/construction/$orgId/construction-dashboard': typeof ConstructionOrgIdConstructionDashboardRoute
  '/construction/$orgId/construction-documents': typeof ConstructionOrgIdConstructionDocumentsRoute
  '/construction/$orgId/construction-projects': typeof ConstructionOrgIdConstructionProjectsRoute
  '/construction/$orgId/construction-tasks': typeof ConstructionOrgIdConstructionTasksRoute
  '/construction/$orgId/construction-teams': typeof ConstructionOrgIdConstructionTeamsRoute
  '/construction/$orgId/members': typeof ConstructionOrgIdMembersRoute
  '/construction/$orgId/projects': typeof ConstructionOrgIdProjectsRouteWithChildren
  '/construction/$orgId/settings': typeof ConstructionOrgIdSettingsRoute
  '/construction/$orgId/teams': typeof ConstructionOrgIdTeamsRoute
  '/construction/$orgId/team/$teamId': typeof ConstructionOrgIdTeamTeamIdRouteWithChildren
  '/construction/$orgId/projects/$projectId/analytics': typeof ConstructionOrgIdProjectsProjectIdAnalyticsRoute
  '/construction/$orgId/projects/$projectId/overview': typeof ConstructionOrgIdProjectsProjectIdOverviewRoute
  '/construction/$orgId/projects/$projectId/settings': typeof ConstructionOrgIdProjectsProjectIdSettingsRoute
  '/construction/$orgId/projects/$projectId/tasks': typeof ConstructionOrgIdProjectsProjectIdTasksRoute
  '/construction/$orgId/projects/$projectId/team': typeof ConstructionOrgIdProjectsProjectIdTeamRoute
  '/construction/$orgId/team/$teamId/all': typeof ConstructionOrgIdTeamTeamIdAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgId'
    | '/auth'
    | '/construction/$orgId/admin'
    | '/construction/$orgId/attachments'
    | '/construction/$orgId/construction-dashboard'
    | '/construction/$orgId/construction-documents'
    | '/construction/$orgId/construction-projects'
    | '/construction/$orgId/construction-tasks'
    | '/construction/$orgId/construction-teams'
    | '/construction/$orgId/members'
    | '/construction/$orgId/projects'
    | '/construction/$orgId/settings'
    | '/construction/$orgId/teams'
    | '/construction/$orgId/team/$teamId'
    | '/construction/$orgId/projects/$projectId/analytics'
    | '/construction/$orgId/projects/$projectId/overview'
    | '/construction/$orgId/projects/$projectId/settings'
    | '/construction/$orgId/projects/$projectId/tasks'
    | '/construction/$orgId/projects/$projectId/team'
    | '/construction/$orgId/team/$teamId/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgId'
    | '/auth'
    | '/construction/$orgId/admin'
    | '/construction/$orgId/attachments'
    | '/construction/$orgId/construction-dashboard'
    | '/construction/$orgId/construction-documents'
    | '/construction/$orgId/construction-projects'
    | '/construction/$orgId/construction-tasks'
    | '/construction/$orgId/construction-teams'
    | '/construction/$orgId/members'
    | '/construction/$orgId/projects'
    | '/construction/$orgId/settings'
    | '/construction/$orgId/teams'
    | '/construction/$orgId/team/$teamId'
    | '/construction/$orgId/projects/$projectId/analytics'
    | '/construction/$orgId/projects/$projectId/overview'
    | '/construction/$orgId/projects/$projectId/settings'
    | '/construction/$orgId/projects/$projectId/tasks'
    | '/construction/$orgId/projects/$projectId/team'
    | '/construction/$orgId/team/$teamId/all'
  id:
    | '__root__'
    | '/'
    | '/$orgId'
    | '/auth'
    | '/construction/$orgId/admin'
    | '/construction/$orgId/attachments'
    | '/construction/$orgId/construction-dashboard'
    | '/construction/$orgId/construction-documents'
    | '/construction/$orgId/construction-projects'
    | '/construction/$orgId/construction-tasks'
    | '/construction/$orgId/construction-teams'
    | '/construction/$orgId/members'
    | '/construction/$orgId/projects'
    | '/construction/$orgId/settings'
    | '/construction/$orgId/teams'
    | '/construction/$orgId/team/$teamId'
    | '/construction/$orgId/projects/$projectId/analytics'
    | '/construction/$orgId/projects/$projectId/overview'
    | '/construction/$orgId/projects/$projectId/settings'
    | '/construction/$orgId/projects/$projectId/tasks'
    | '/construction/$orgId/projects/$projectId/team'
    | '/construction/$orgId/team/$teamId/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgIdRoute: typeof OrgIdRoute
  AuthRoute: typeof AuthRoute
  ConstructionOrgIdAdminRoute: typeof ConstructionOrgIdAdminRoute
  ConstructionOrgIdAttachmentsRoute: typeof ConstructionOrgIdAttachmentsRoute
  ConstructionOrgIdConstructionDashboardRoute: typeof ConstructionOrgIdConstructionDashboardRoute
  ConstructionOrgIdConstructionDocumentsRoute: typeof ConstructionOrgIdConstructionDocumentsRoute
  ConstructionOrgIdConstructionProjectsRoute: typeof ConstructionOrgIdConstructionProjectsRoute
  ConstructionOrgIdConstructionTasksRoute: typeof ConstructionOrgIdConstructionTasksRoute
  ConstructionOrgIdConstructionTeamsRoute: typeof ConstructionOrgIdConstructionTeamsRoute
  ConstructionOrgIdMembersRoute: typeof ConstructionOrgIdMembersRoute
  ConstructionOrgIdProjectsRoute: typeof ConstructionOrgIdProjectsRouteWithChildren
  ConstructionOrgIdSettingsRoute: typeof ConstructionOrgIdSettingsRoute
  ConstructionOrgIdTeamsRoute: typeof ConstructionOrgIdTeamsRoute
  ConstructionOrgIdTeamTeamIdRoute: typeof ConstructionOrgIdTeamTeamIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgId': {
      id: '/$orgId'
      path: '/$orgId'
      fullPath: '/$orgId'
      preLoaderRoute: typeof OrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/teams': {
      id: '/construction/$orgId/teams'
      path: '/construction/$orgId/teams'
      fullPath: '/construction/$orgId/teams'
      preLoaderRoute: typeof ConstructionOrgIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/settings': {
      id: '/construction/$orgId/settings'
      path: '/construction/$orgId/settings'
      fullPath: '/construction/$orgId/settings'
      preLoaderRoute: typeof ConstructionOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/projects': {
      id: '/construction/$orgId/projects'
      path: '/construction/$orgId/projects'
      fullPath: '/construction/$orgId/projects'
      preLoaderRoute: typeof ConstructionOrgIdProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/members': {
      id: '/construction/$orgId/members'
      path: '/construction/$orgId/members'
      fullPath: '/construction/$orgId/members'
      preLoaderRoute: typeof ConstructionOrgIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/construction-teams': {
      id: '/construction/$orgId/construction-teams'
      path: '/construction/$orgId/construction-teams'
      fullPath: '/construction/$orgId/construction-teams'
      preLoaderRoute: typeof ConstructionOrgIdConstructionTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/construction-tasks': {
      id: '/construction/$orgId/construction-tasks'
      path: '/construction/$orgId/construction-tasks'
      fullPath: '/construction/$orgId/construction-tasks'
      preLoaderRoute: typeof ConstructionOrgIdConstructionTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/construction-projects': {
      id: '/construction/$orgId/construction-projects'
      path: '/construction/$orgId/construction-projects'
      fullPath: '/construction/$orgId/construction-projects'
      preLoaderRoute: typeof ConstructionOrgIdConstructionProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/construction-documents': {
      id: '/construction/$orgId/construction-documents'
      path: '/construction/$orgId/construction-documents'
      fullPath: '/construction/$orgId/construction-documents'
      preLoaderRoute: typeof ConstructionOrgIdConstructionDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/construction-dashboard': {
      id: '/construction/$orgId/construction-dashboard'
      path: '/construction/$orgId/construction-dashboard'
      fullPath: '/construction/$orgId/construction-dashboard'
      preLoaderRoute: typeof ConstructionOrgIdConstructionDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/attachments': {
      id: '/construction/$orgId/attachments'
      path: '/construction/$orgId/attachments'
      fullPath: '/construction/$orgId/attachments'
      preLoaderRoute: typeof ConstructionOrgIdAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/admin': {
      id: '/construction/$orgId/admin'
      path: '/construction/$orgId/admin'
      fullPath: '/construction/$orgId/admin'
      preLoaderRoute: typeof ConstructionOrgIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/team/$teamId': {
      id: '/construction/$orgId/team/$teamId'
      path: '/construction/$orgId/team/$teamId'
      fullPath: '/construction/$orgId/team/$teamId'
      preLoaderRoute: typeof ConstructionOrgIdTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction/$orgId/team/$teamId/all': {
      id: '/construction/$orgId/team/$teamId/all'
      path: '/all'
      fullPath: '/construction/$orgId/team/$teamId/all'
      preLoaderRoute: typeof ConstructionOrgIdTeamTeamIdAllRouteImport
      parentRoute: typeof ConstructionOrgIdTeamTeamIdRoute
    }
    '/construction/$orgId/projects/$projectId/team': {
      id: '/construction/$orgId/projects/$projectId/team'
      path: '/$projectId/team'
      fullPath: '/construction/$orgId/projects/$projectId/team'
      preLoaderRoute: typeof ConstructionOrgIdProjectsProjectIdTeamRouteImport
      parentRoute: typeof ConstructionOrgIdProjectsRoute
    }
    '/construction/$orgId/projects/$projectId/tasks': {
      id: '/construction/$orgId/projects/$projectId/tasks'
      path: '/$projectId/tasks'
      fullPath: '/construction/$orgId/projects/$projectId/tasks'
      preLoaderRoute: typeof ConstructionOrgIdProjectsProjectIdTasksRouteImport
      parentRoute: typeof ConstructionOrgIdProjectsRoute
    }
    '/construction/$orgId/projects/$projectId/settings': {
      id: '/construction/$orgId/projects/$projectId/settings'
      path: '/$projectId/settings'
      fullPath: '/construction/$orgId/projects/$projectId/settings'
      preLoaderRoute: typeof ConstructionOrgIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ConstructionOrgIdProjectsRoute
    }
    '/construction/$orgId/projects/$projectId/overview': {
      id: '/construction/$orgId/projects/$projectId/overview'
      path: '/$projectId/overview'
      fullPath: '/construction/$orgId/projects/$projectId/overview'
      preLoaderRoute: typeof ConstructionOrgIdProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ConstructionOrgIdProjectsRoute
    }
    '/construction/$orgId/projects/$projectId/analytics': {
      id: '/construction/$orgId/projects/$projectId/analytics'
      path: '/$projectId/analytics'
      fullPath: '/construction/$orgId/projects/$projectId/analytics'
      preLoaderRoute: typeof ConstructionOrgIdProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof ConstructionOrgIdProjectsRoute
    }
  }
}

interface ConstructionOrgIdProjectsRouteChildren {
  ConstructionOrgIdProjectsProjectIdAnalyticsRoute: typeof ConstructionOrgIdProjectsProjectIdAnalyticsRoute
  ConstructionOrgIdProjectsProjectIdOverviewRoute: typeof ConstructionOrgIdProjectsProjectIdOverviewRoute
  ConstructionOrgIdProjectsProjectIdSettingsRoute: typeof ConstructionOrgIdProjectsProjectIdSettingsRoute
  ConstructionOrgIdProjectsProjectIdTasksRoute: typeof ConstructionOrgIdProjectsProjectIdTasksRoute
  ConstructionOrgIdProjectsProjectIdTeamRoute: typeof ConstructionOrgIdProjectsProjectIdTeamRoute
}

const ConstructionOrgIdProjectsRouteChildren: ConstructionOrgIdProjectsRouteChildren =
  {
    ConstructionOrgIdProjectsProjectIdAnalyticsRoute:
      ConstructionOrgIdProjectsProjectIdAnalyticsRoute,
    ConstructionOrgIdProjectsProjectIdOverviewRoute:
      ConstructionOrgIdProjectsProjectIdOverviewRoute,
    ConstructionOrgIdProjectsProjectIdSettingsRoute:
      ConstructionOrgIdProjectsProjectIdSettingsRoute,
    ConstructionOrgIdProjectsProjectIdTasksRoute:
      ConstructionOrgIdProjectsProjectIdTasksRoute,
    ConstructionOrgIdProjectsProjectIdTeamRoute:
      ConstructionOrgIdProjectsProjectIdTeamRoute,
  }

const ConstructionOrgIdProjectsRouteWithChildren =
  ConstructionOrgIdProjectsRoute._addFileChildren(
    ConstructionOrgIdProjectsRouteChildren,
  )

interface ConstructionOrgIdTeamTeamIdRouteChildren {
  ConstructionOrgIdTeamTeamIdAllRoute: typeof ConstructionOrgIdTeamTeamIdAllRoute
}

const ConstructionOrgIdTeamTeamIdRouteChildren: ConstructionOrgIdTeamTeamIdRouteChildren =
  {
    ConstructionOrgIdTeamTeamIdAllRoute: ConstructionOrgIdTeamTeamIdAllRoute,
  }

const ConstructionOrgIdTeamTeamIdRouteWithChildren =
  ConstructionOrgIdTeamTeamIdRoute._addFileChildren(
    ConstructionOrgIdTeamTeamIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgIdRoute: OrgIdRoute,
  AuthRoute: AuthRoute,
  ConstructionOrgIdAdminRoute: ConstructionOrgIdAdminRoute,
  ConstructionOrgIdAttachmentsRoute: ConstructionOrgIdAttachmentsRoute,
  ConstructionOrgIdConstructionDashboardRoute:
    ConstructionOrgIdConstructionDashboardRoute,
  ConstructionOrgIdConstructionDocumentsRoute:
    ConstructionOrgIdConstructionDocumentsRoute,
  ConstructionOrgIdConstructionProjectsRoute:
    ConstructionOrgIdConstructionProjectsRoute,
  ConstructionOrgIdConstructionTasksRoute:
    ConstructionOrgIdConstructionTasksRoute,
  ConstructionOrgIdConstructionTeamsRoute:
    ConstructionOrgIdConstructionTeamsRoute,
  ConstructionOrgIdMembersRoute: ConstructionOrgIdMembersRoute,
  ConstructionOrgIdProjectsRoute: ConstructionOrgIdProjectsRouteWithChildren,
  ConstructionOrgIdSettingsRoute: ConstructionOrgIdSettingsRoute,
  ConstructionOrgIdTeamsRoute: ConstructionOrgIdTeamsRoute,
  ConstructionOrgIdTeamTeamIdRoute:
    ConstructionOrgIdTeamTeamIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
